name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Run tests
        run: ./kotlin test
      # TODO: delete that
      - name: Replace version key by tag in `client/module.yaml`
        run: "sed -i -E 's/^([[:space:]]*)#[[:space:]]*version:.*/\1version: ${{ github.event.release.tag_name }}/' client/module.yaml"
      - name: Show `client/module.yaml`
        run: cat client/module.yaml