name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build with Gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          # jobs with different JDK versions can't share caches
          job-id: jdk17
          arguments: build
