name: Publish on release

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Run tests
        run: ./kotlin test
      - name: Create credential file
        run: |
          echo "spaceUsername=${{ secrets.JB_SPACE_CLIENT_ID }}" > credentials.properties
          echo "spacePassword=${{ secrets.JB_SPACE_CLIENT_SECRET }}" >> credentials.properties
      - name: Replace version key by tag in `client/module.yaml`
        run: "sed -i -E 's/^([[:space:]]*)#[[:space:]]*version:.*/\\1version: ${{ github.event.release.tag_name }}/' client/module.yaml"
      - name: Publish to Space Packages
        run: ./kotlin publish toSpace
